#!/bin/bash

INTERVALS_DIR="../ChIP-seq/train_intervals"
INTERVAL_FILES=$(ls ${INTERVALS_DIR})
FILE_EXTENSION=".chipseq.train.interval"

for INTERVAL_FILE in ${INTERVAL_FILES}; do
    INTERVAL_DIR=${INTERVAL_FILE:0:${#INTERVAL_FILE}-${#FILE_EXTENSION}}
    mkdir ${INTERVAL_DIR}
    ln -s ${PWD}/${INTERVALS_DIR}/${INTERVAL_FILE} ${INTERVAL_DIR}
done