################################################################
## Import functions 
import os
import itertools
from snakemake.utils import R

################################################################
## Environment variables
RSAT = os.environ['RSAT']

################################################################
## Define data + output folders
MAIN_DIR = ""
DATA_DIR = os.path.join(MAIN_DIR, "data")
MOTIFS_DIR = os.path.join(DATA_DIR, "motifs")
TABLES_DIR = os.path.join(DATA_DIR, "annotation_tables")
RESULTS_DIR = os.path.join(MAIN_DIR, "results")
ANNOTATIONS_DIR = os.path.join(RESULTS_DIR, "annotations")

################################################################
## Parameters Variables (used in different rules)

## Taxa
TAXA = "vertebrates insects plants nematodes fungi".split()
#TAXA = "insects nematodes fungi".split()
#TAXA = "nematodes".split()
#TAXA = "plants".split()


################################################################
## One target to rule them all

PARSE_CORE_MOTIF_IDS = expand(os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_CORE_{taxon}.tf"), taxon = TAXA)
PARSE_NV_MOTIF_IDS = expand(os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_{taxon}.tf"), taxon = TAXA)
CLUSTERING_INTERACTIVE = expand(os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "interactive_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}_SUMMARY.html"), taxon = TAXA)
CONCAT_CORE_UNVALIDATED_MOTIFS = expand(os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_+_CORE_{taxon}.tf"), taxon = TAXA)
CONCAT_CORE_UNVALIDATED_ANNOTATIONS = expand(os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations.tsv"), taxon = TAXA)
PARSE_ANNOTATION_TABLES = expand(os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations_with_colours.tsv"), taxon = TAXA)
HTML_TF_CLASS_COLOUR = expand(os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_TF_class_colours.html"), taxon = TAXA)
CLUSTERING_RADIAL = expand(os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "radial_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}_radial_tree.html"), taxon = TAXA)


rule all:
    input: PARSE_CORE_MOTIF_IDS, \
           PARSE_NV_MOTIF_IDS, \
           CONCAT_CORE_UNVALIDATED_MOTIFS, \
           CONCAT_CORE_UNVALIDATED_ANNOTATIONS, \
           PARSE_ANNOTATION_TABLES, \
           HTML_TF_CLASS_COLOUR, \
           CLUSTERING_RADIAL, \
           CLUSTERING_INTERACTIVE, \
	   

           
rule parse_CORE_motif_IDs:
	"""
	"""
	input:
            os.path.join(MOTIFS_DIR, "JASPAR2020_CORE_{taxon}_non-redundant_pfms_transfac.txt")
	output:
            os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_CORE_{taxon}.tf")
	message:
            "Parsing JASPAR 2020 CORE {wildcards.taxon} motif IDs"
	shell:
            """
            perl -lne  'if($_ =~ /^AC/ || $_ =~ /^ID/){{ $_ =~ s/\(/_/gi; s/\)/_/gi; s/\./_/gi; }}; if($_ =~ /^ID(\s+)(.+)/){{ $_ = "ID".$1.$2}} print $_;' {input} > {output}
            """


rule parse_NonValidated_motif_IDs:
	"""
	"""
	input:
            os.path.join(MOTIFS_DIR, "JASPAR2020_UNVALIDATED_{taxon}_redundant_pfms_transfac.txt")
	output:
            os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_{taxon}.tf")
	message:
            "Parsing JASPAR 2020 Unvalidated {wildcards.taxon} motif IDs"
	shell:
            """
            perl -lne  'if($_ =~ /^AC/ || $_ =~ /^ID/){{ $_ =~ s/\(/_/gi; s/\)/_/gi; s/\./_/gi; }}; if($_ =~ /^ID(\s+)(.+)/){{ $_ = "ID".$1."*".$2}} print $_;' {input} > {output}
            """


rule CLUSTER_MATRICES_HTML_REPORT:
    """  
    """
    input:
        CORE = os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_CORE_{taxon}.tf"), \
        UNVALIDATED = os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_{taxon}.tf")
    output:
        os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "interactive_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}_SUMMARY.html")
    message:
        "Clustering JASPAR 2020 {wildcards.taxon} - HTML report"
    params: v = "2", \
	    prefix = os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "interactive_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}")
    shell:
        """
        matrix-clustering -v {params.v} -matrix CORE_{wildcards.taxon} {input.CORE} tf -matrix NV_{wildcards.taxon} {input.UNVALIDATED} tf -hclust_method average -calc sum -title "JASPAR 2020 {wildcards.taxon}" -metric_build_tree Ncor -lth w 5 -lth cor 0.6 -lth Ncor 0.4 -label_in_tree name -return json,heatmap -calc mean -quick -o {params.prefix}
        """


rule concat_CORE_Unvalidated_motifs:
    """
    """
    input:
        CORE = os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_CORE_{taxon}.tf"), \
        UNVALIDATED = os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_{taxon}.tf")
    output:
        os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_+_CORE_{taxon}.tf")
    message:
        "Concatenating CORE + Unvalidated motifs {wildcards.taxon}"
    shell:
        """
        cat {input.CORE} {input.UNVALIDATED} > {output}
        """


rule concat_CORE_Unvalidated_annotation_tables:
    """
    """
    input:
        CORE = os.path.join(TABLES_DIR, "jaspar2020_{taxon}_annotations_CORE.tsv"), \
        UNVALIDATED = os.path.join(TABLES_DIR, "jaspar2020_{taxon}_annotations_Unvalidated.tsv")
    output:
        os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations.tsv")
    message:
        "Concatenating CORE + Unvalidated motifs {wildcards.taxon}"
    shell:
        """
        cat {input.CORE} {input.UNVALIDATED}  > {output}
        """


rule assign_TF_class_colours:
	"""
	"""
	input:
           os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations.tsv")
	output:
            annotation = os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations_with_colours.tsv"), \
            html_table = os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_TF_class_colours.html")
	message:
            "Assigning TF class <-> colours for JASPAR 2020 {wildcards.taxon}"
	shell:
            """
            Rscript bin/TF_Family_color_assignation.R -i {input} -o {output.annotation} -c {output.html_table}
            """


rule CLUSTER_MATRICES_RADIAL:
    """  
    """
    input:
        matrix = os.path.join(MOTIFS_DIR, "Motifs_parsed_ID", "JASPAR2020_Unvalidated_+_CORE_{taxon}.tf"),\
	link_table = os.path.join(ANNOTATIONS_DIR, "{taxon}", "jaspar2020_{taxon}_Unvalidated_+_CORE_annotations_with_colours.tsv")
    output:
        os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "radial_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}_radial_tree.html")
    message:
        " Clustering JASPAR 2020 {wildcards.taxon} - HTML radial tree"
    params:
        v = "2", \
	prefix = os.path.join(RESULTS_DIR, "JASPAR_2020_matrix_clustering", "{taxon}_CORE_+_UNVALIDATED", "radial_trees", "JASPAR_2020_CORE_+_UNVALIDATED_matrix_clustering_{taxon}")
    shell:
        """
        matrix-clustering -v {params.v} -matrix JASPAR_2020_CORE_+_UNVALIDATED_{wildcards.taxon} {input.matrix} tf -hclust_method average -calc sum -title "JASPAR 2020 {wildcards.taxon}" -metric_build_tree Ncor -lth w 5 -lth cor 0.7 -lth Ncor 0.5 -label_in_tree name -return json -quick -radial_tree_only -o {params.prefix} -calc mean -ID_link_color_table {input.link_table}
        """



