################################################################
author: Oriol_Fornes

###############################
## Expected folder structure ##
###############################
## The Snakefile will launch a motif analysis + calculate centrality for each
## discovered motifs for every set of peaks in Narrowpeak format found in the
## "data".
##
## Example:
##
## cd data
##
## ...
## ├── TIGD3.Plate_2_H4_S128.PEAKS990017
## │   └── TIGD3.Plate_2_H4_S128.PEAKS990017.chipseq.train.interval
## ...
## └── ZBED5.Plate_1_D3_S20.PEAKS990013
## │   └── ZBED5.Plate_1_D3_S20.PEAKS990013.chipseq.train.interval
## ...
##
## Every EXPERIMENT_FOLDER in the data folder must contain a narrowPeak file
## with the same name, see tree above. This is the data structure required by
## the pipeline.

## === ##
## Bin ##
## === ##
bin : /Users/ofornes/GitHub/JASPAR-Motif-Discovery/bin
python : /home_local/ofornes/Miniconda3/envs/rsat/bin/python
RSAT : /home_local/ofornes/Miniconda3/envs/rsat/share/rsat
TFBS : /home_local/ofornes/Miniconda3/envs/tfbs/bin

## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25
central_pvalue : -200

## ============================================= ##
## GRECO-BIT: folders and required input files   ##
## ============================================= ##
genome_fasta : /home_local/ofornes/JASPAR-motif-discovery/databases/genomes/hg38.fa
genome_size : /home_local/ofornes/JASPAR-motif-discovery/databases/genomes/hg38.chrom.sizes
motif_databases : /home_local/ofornes/JASPAR-motif-discovery/databases/motifs
data_dir : /home_local/ofornes/JASPAR-motif-discovery/GRECO-BIT/data
out_dir : /home_local/ofornes/JASPAR-motif-discovery/GRECO-BIT/output
curation_dir : /home_local/ofornes/JASPAR-motif-discovery/GRECO-BIT/curation
